package com.tverts.shunts.protocol;

/* com.tverts: support */

import com.tverts.support.SU;


/**
 * An exception that had occurred while running
 * the shunt protocol.
 *
 * Note that this exception is of that system
 * errors that are generated by the responding
 * side while executing the shunts.
 *
 * @author anton.baukin@gmail.com
 */
public class   SeShProtocolError
       extends Exception
{
	/* public: constructors */

	public SeShProtocolError()
	{}

	public SeShProtocolError(Object... message)
	{
		super(SU.cats(message));
	}

	public SeShProtocolError(Throwable cause)
	{
		super(cause);
	}

	public SeShProtocolError(Throwable cause, Object... message)
	{
		super(SU.sYs(SU.cats(message)), cause);
	}
}